[colors.primary]
background = "#000000"
foreground = "#dddddd"

[colors.cursor]
cursor = '#ff4949'

[colors.normal]
black   = '#aaaaaa'
red     = '#dd1717'
green   = '#0f4392'
yellow  = '#ff4949'
blue    = '#aa0202'
magenta = '#2266dd'
cyan    = '#4444dd'
white   = '#eeeeee'

[colors.bright]
black   = '#aaaaaa'
red     = '#dd1717'
green   = '#0f4392'
yellow  = '#ff4949'
blue    = '#aa0202'
magenta = '#2266dd'
cyan    = '#4444dd'
white   = '#eeeeee'

[colors.selection]
text = "#000000"
background = "#dddddd"

[window]
opacity = 0.75
decorations = "none"
blur = true
padding = {x = 0, y = 0}

[window.dimensions]
columns = 255
lines = 63

[font]
size = 14.0
#normal = { family = "Adwaita mono", style = "regular" }
#builtin_box_drawing = true
